server:
  port: 9200
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://192.168.100.11:8848/nacos
    routes:
      - name: 用户服务
        serviceName: demo-user
        location: /v2/api-docs?group=2.X版本
        servicePath: /